feat: clarified language in localization tutorial using feedback
ethyca/fidesdocs pull request #194
Opened 2023-08-14 18:23 UTC by nicolas-ethyca

2023-08-14 18:31 UTC, NevilleS requested changes
Bit confusing!

2023-08-14 18:31 UTC, NevilleS commented on pages/tutorials/consent-management-configuration/privacy-notices-localization.mdx
> +For example, you can create multiple notices that use the same `data_sales_and_sharing` key for integrations, but different locations for different languages.
Can you update the `Privacy Notice Configuration` section above instead? In there you say "...a unique key for cookie consent configuration" but now that conflicts with this 😬 

I'd recommend rewriting that section to basically just suggest that they copy the data uses and key from an existing notice, and then just change the location.

2023-08-14 18:43 UTC, nicolas-ethyca commented on pages/tutorials/consent-management-configuration/privacy-notices-localization.mdx
> +For example, you can create multiple notices that use the same `data_sales_and_sharing` key for integrations, but different locations for different languages.
@NevilleS how about now?

2023-08-20 16:43 UTC, NevilleS approved these changes
This change will help, thanks, so I'd vote to merge it in.

That saidI think it's still confusing though. We don't _really_ explain how to duplicate an existing notice and configure different, location-specific language, so if we tested this on a person I think they'd still be confused. I'm not exactly sure *what* I'm looking for, but it'd probably be something that covers:
* why you'd want to create a location-specific notice
* how you'd duplicate an existing notice and configure up
* why you'd reuse the same notice key (so you don't need to update GTM/etc.)
* etc.

...but perfection is the enemy of good so let's make this change to make it clear that this is optional thanks

2023-08-23 17:56 UTC, merged