saas connector creation docs
ethyca/fidesdocs pull request #22
Opened 2022-12-21 22:19 UTC by conceptualshark

Closes DOX-238

### Description of Changes

* Import the documentation on creating your own saas connector from scratch.

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created

2023-01-04 14:56 UTC, mfbrown commented on pages/fides/dsr_quickstart/saas_connectors/create_connectors.md
> +The following is example Dataset declaration, representing a simple `conversations` table:
Edit to "The following is an example Dataset declaration, representing a simple `conversations` table:"

2023-01-04 20:34 UTC, mfbrown requested changes

2023-01-04 20:34 UTC, mfbrown commented on pages/fides/dsr_quickstart/saas_connectors/create_connectors.md
> +| `fields` | Description |
This isn't rendering correctly:
![Screen Shot 2023-01-04 at 3 15 24 PM](https://user-images.githubusercontent.com/4807009/210641847-a8e84f8e-1aed-4f6b-86c7-43c18168aaeb.png)

2023-01-04 20:34 UTC, mfbrown commented on pages/fides/dsr_quickstart/saas_connectors/create_connectors.md
> +          - name: id
This needs to be updated to `user.unique_id`

![Screen Shot 2023-01-04 at 3 19 59 PM](https://user-images.githubusercontent.com/4807009/210642639-e803b396-8873-4756-9c5e-c025561100cb.png)

2023-01-04 20:34 UTC, mfbrown commented on pages/fides/dsr_quickstart/saas_connectors/create_connectors.md
> +          - name: id
To be clear it's the data category that needs to be updated

2023-01-04 20:34 UTC, mfbrown commented on pages/fides/dsr_quickstart/saas_connectors/create_connectors.md
> +The following is an example SaaS config declaration, which consists of a single HTTP request, and references the fields defined in the above dataset:
I'm not sure this actually references the above dataset example

2023-01-04 20:34 UTC, mfbrown commented on pages/fides/dsr_quickstart/saas_connectors/create_connectors.md
> +    *  The domain and authentication requirements for an HTTP client - in this case, [Mailchimp](./example_configs/mailchimp)
Following up on my previous comment, this needs to change OR  we need to update the dataset to use a Mailchimp dataset. 

I'd prefer we use an example dataset like Mailchimp which is probably easier for someone to grasp and reference quickly.

2023-01-10 15:36 UTC, malaethyca commented on pages/fides/dsr_quickstart/saas_connectors/create_connectors.md
> +| `fields` | Description |
@suchiroll

2023-01-10 15:38 UTC, malaethyca commented on pages/fides/dsr_quickstart/saas_connectors/create_connectors.md
> +          - name: id
@mfbrown Can you please clarify this for Lalitha?

2023-01-11 14:40 UTC, mfbrown commented on pages/fides/dsr_quickstart/saas_connectors/create_connectors.md
> +The following is example Dataset declaration, representing a simple `conversations` table:
This is in Line 13. Just need to add "an"

2023-01-11 14:43 UTC, mfbrown commented on pages/fides/dsr_quickstart/saas_connectors/create_connectors.md
> +| `fields` | Description |
Looks like we're missing `| -- | ----- |` between lines 53 and 54

2023-02-15 07:58 UTC, ThomasLaPiana commented
@mfbrown do you have the bandwidth to get this over the line? Seems like you're pretty familiar with what was going on here

2023-04-07 16:01 UTC, galvana commented
@mfbrown this PR can be replaced by https://github.com/ethyca/fidesdocs/pull/86

2023-04-13 23:00 UTC, closed without merging