56 update docs with regards to new storage and messaging config functionality
ethyca/fidesdocs pull request #67
Opened 2023-02-28 03:09 UTC by adamsachs

Closes #56 

### Description of Changes

* updates to docs for new storage and messaging functionality
* some basic steps for new UI-based config
* new APIs are also covered

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created

2023-02-28 15:36 UTC, adamsachs commented
the UI work here still isn't merged into `main` (or released for that matter), so i'm not sure when to begin formal review on these changes.

but i did want to give a heads up if anyone has the time to take a preliminary look. this is a (hopefully pretty polished) draft that i'd like to get into our docs once the new functionality is fully released.

2023-03-02 15:09 UTC, adamsachs commented
@mfbrown added you as a reviewer per discussion that product is "owning" docs, and also because you've tested the new UI hands-on!

i think the doc updates are just about ready to be looked at whenever, i'm just holding on opening this up formally for review until we actually get the UI merged into `main`.

2023-03-08 17:59 UTC, RobertKeyser requested changes
Awesome work! A few minor things.

2023-03-08 17:59 UTC, RobertKeyser commented on pages/fides/configuration/messaging_services.md
> +When your users submit a privacy request, you may may want to send them messages to do things such as verify their identity or keep them informed of progress on their privacy request. Fides supports
```suggestion
When your users submit a privacy request, you may want to send them messages to do things such as verify their identity or keep them informed of progress on their privacy request. Fides supports email and SMS service configurations for sending processing notifications to your users.
```

2023-03-08 17:59 UTC, RobertKeyser commented on pages/fides/configuration/messaging_services.md
> +Fides currently supports <a href="https://www.mailgun.com" target="_blank">Mailgun</a> and <a href="https://www.twilio.com/en-us/sendgrid" target="_blank">Twilio (SendGrid)</a> for email messaging, a
Do we also officially support Mandrill/Mailchimp transactional yet?

2023-03-08 17:59 UTC, RobertKeyser commented on pages/fides/configuration/messaging_services.md
> +Last, you'll need to update global application settings related to messaging, to ensure messages are sent at the desired points and using the messaging configuration of your choice. Here you can also
Nit:

```suggestion
Lastly, you'll need to update global application settings related to messaging, to ensure messages are sent at the desired points and using the messaging configuration of your choice. Here you can also specify whether you'd like to require subject identity verification on privacy requests, which will also use the specified messaging configuration.
```

2023-03-08 17:59 UTC, RobertKeyser commented on pages/fides/configuration/storage.md
> +<Callout> Out of the box, Fides assumes a `Local` storage destination as the active storage destination used, by default, for all policy rules that do not have ay storage destination configured. This
"Out of the box" and "by default" are repetitive, let's go with only one.

```suggestion
<Callout> Out of the box, Fides assumes a `Local` storage destination as the active storage destination used for all policy rules that do not have ay storage destination configured. This is not recommended for production use cases, so users are encouraged to configure a default S3 storage destination, either through the UI or with the API calls described here. </Callout>
```

2023-03-08 17:59 UTC, RobertKeyser commented on pages/fides/configuration/storage.md
> +<Callout> Out of the box, Fides assumes a `Local` storage destination as the active storage destination used, by default, for all policy rules that do not have ay storage destination configured. This
Not recommended seems a bit too weak of a phrase for this. I think we _should_ use "should" instead.

```suggestion
<Callout> Out of the box, Fides assumes a `Local` storage destination as the active storage destination used, by default, for all policy rules that do not have ay storage destination configured. This should not be used for production use cases, so users should configure a default S3 storage destination, either through the UI or with the API calls described here. </Callout>
```

2023-03-08 17:59 UTC, RobertKeyser commented on pages/fides/configuration/storage.md
> +If you want even finer grained control and do not want to only rely on a _default_ storage configuration, you can also configure _manual_ storage configurations and explicitly associate them with giv
https://en.wiktionary.org/wiki/fine-grained#:~:text=fine-grained%20(comparative%20more%20fine,(figurative)%20Highly%20detailed.

```suggestion
If you want even more fine-grained control and do not want to only rely on a _default_ storage configuration, you can also configure _manual_ storage configurations and explicitly associate them with given policy rules. This allows you to output particular types of requested data to particular storage destinations, for example.
```

2023-03-09 16:43 UTC, adamsachs commented on pages/fides/configuration/messaging_services.md
> +Fides currently supports <a href="https://www.mailgun.com" target="_blank">Mailgun</a> and <a href="https://www.twilio.com/en-us/sendgrid" target="_blank">Twilio (SendGrid)</a> for email messaging, a
we do as of `2.8.0` but unfortunately do not have it supported to be UI configurable yet. we could still mention it here with that caveat?

2023-03-09 16:44 UTC, adamsachs commented on pages/fides/configuration/messaging_services.md
> +Last, you'll need to update global application settings related to messaging, to ensure messages are sent at the desired points and using the messaging configuration of your choice. Here you can also
heh i actually had `lastly` and thought it sounded weird, but i think it was just a case of me overthinking wording...i will take your suggestion as indication that i should have gone with my instinct :)

2023-03-09 16:46 UTC, adamsachs commented on pages/fides/configuration/storage.md
> +<Callout> Out of the box, Fides assumes a `Local` storage destination as the active storage destination used, by default, for all policy rules that do not have ay storage destination configured. This
👍 for sure - good call here.

2023-03-09 16:46 UTC, adamsachs commented on pages/fides/configuration/storage.md
> +If you want even finer grained control and do not want to only rely on a _default_ storage configuration, you can also configure _manual_ storage configurations and explicitly associate them with giv
:)

2023-03-09 16:47 UTC, adamsachs commented on pages/fides/configuration/storage.md
> +If you want even finer grained control and do not want to only rely on a _default_ storage configuration, you can also configure _manual_ storage configurations and explicitly associate them with giv
how about "less coarse grained" :trollface:

2023-03-09 16:56 UTC, adamsachs commented on pages/fides/configuration/messaging_services.md
> +Fides currently supports <a href="https://www.mailgun.com" target="_blank">Mailgun</a> and <a href="https://www.twilio.com/en-us/sendgrid" target="_blank">Twilio (SendGrid)</a> for email messaging, a
ehh i'm actually going to say that we should not mention it yet, let's log another doc issue to cover this. it feels weird mentioning it here and then not mentioning it anywhere else. and i don't quite have enough background on it (at least not yet) to make that broader doc update. so i'd prefer to get my changes here in place now, and split out the mailchimp transactional doc work. i don't think we've even fully validated the functionality yet, it's very bleeding edge still :)

2023-03-14 20:49 UTC, merged